### PR TITLE
Add meta-JEP for new JEP process

### PR DESCRIPTION
**Pull request by captainsafia**
This is the meta-JEP for the new JEP workflow that was proposed during NES in early February.

This is a draft of the document that was created during the JEP session. Some more content needs to be added.

The pre-proposal associated with this JEP is https://github.com/jupyter/enhancement-proposals/issues/27.

### CODE REVIEW

**Comment by willingc** [comment]
It would be helpful to give this JEP a number similar to the Python PEP process and merge this version with the current date with a header similar to: https://www.python.org/dev/peps/pep-0580/

For example:

 Item | Value 
-------------|-------
| JEP number | 0029 |
| Title | The JEP process |
| Authors | Safia Abdalla, xxx, xxx |
| Status | Draft |
| Type | P - Process JEP |
| Created | 23-Feb-2019 |
| History | 28-Feb-2019 |

The benefit would be we could merge a starting point and iterate on subsequent PRs instead of one PR with too many comments to be useful.

Thoughts? @captainsafia

**Comment by mckev-amazon** [comment]
@willingc Good call - building a table similar to the one above and specifically assigning a JEP number should probably be the final step of the pre-approval step.  That way, the JEP PR can have the JEP # in the PR contents (PR title, directory name, etc.)

Let's add that detail to the doc.

**Comment by parente** [comment]
Good to see this process being revitalized. Thank you all for working on it.

I started a review with some minor corrections and questions to consider, but then saw @willingc's suggestion that this PR should merge as-is and edits should be made in follow-on PRs. I'll save my comments until it's in.

**Comment by captainsafia** [comment]
@willingc Roger that! I've added the content header.

@mckev-amazon I've added this is as a step.

@parente Sounds good! I'll merge this and feel free to add your edits in a follow-on. Thanks!

**Comment by choldgraf** [comment]
just want to note that I think this is awesome!

Two quick questions:

1. Is there a place that community conversation about the JEP restructuring is happening?

2. To that extent, what's a good process by which new JEPs / status of JEPs / etc can be signaled to the Jupyter community? Maybe the mailing list?

3. One of my favorite things about the Rust RFC process is that they have a [website with all of their RFCs](https://rust-lang.github.io/rfcs/).

   Would folks be interested in a PR that would build a similar website using jupyter-book served ad `jupyter.org/enhancement-proposals`? Would this be something I should submit as a JEP to discuss?

**Comment by captainsafia** [comment]
> Is there a place that community conversation about the JEP restructuring is happening?

This repo probably makes the most sense for conversations to happen.

> To that extent, what's a good process by which new JEPs / status of JEPs / etc can be signaled to the Jupyter community? Maybe the mailing list?

Ideas have been thrown out but more concrete plans (creating a newsletter, creating a Twitter bot that tweets out JEPs) will need to be outlined in future iterations of the JEP.

>  Would folks be interested in a PR that would build a similar website using jupyter-book served ad jupyter.org/enhancement-proposals? Would this be something I should submit as a JEP to discuss?

I think that's a good idea! Feel free to submit a PR adding a new "distribution" header to the existing JEP that outlines a website as one point of sharing about JEPs in the future.

**Comment by willingc** [comment]
@choldgraf Great questions. I think @captainsafia covered the responses. Ideally, most conversation will happen on the repo. Let's revisit after the dev meeting whether an email letting folks know about the JEP reboot would be helpful.

**Comment by lheagy** [comment]
This is really exciting! Thanks @captainsafia for getting this into motion

**Comment by captainsafia** [comment]
No problem! Thanks for jumping on the conversation, @lheagy! Feel free to review this draft and post edits/follow-ups in a PR on the main issue.

**Comment by saulshanabrook** [comment]
This process looks great from my perspective. Thank you all for putting this together! If I had any suggestions would it make sense to propose those as PRs to this file?

**Comment by Zsailer** [comment]
> To that extent, what's a good process by which new JEPs / status of JEPs / etc can be signaled to the Jupyter community? Maybe the mailing list?

@choldgraf do you think a JEP discourse category makes sense (instead of a mailing list)?

**Comment by choldgraf** [comment]
I'd be +1 on creating a category for this on the community forum. I wonder if it'd be best as a top-level category, or a sub-category under "Governance" (https://discourse.jupyter.org/c/governance)?

**Pull request merged**
