### PR TITLE
Added submission guidelines to README

### PR DESCRIPTION
**Pull request by captainsafia**
I figured this would be nice to have. Let me know if it needs changes or is not necessary.

cc/ @ellisonbg @rgbkrk

### CODE REVIEW

**Comment by captainsafia** [comment]
cc/ @minrk @Carreau 

Feel free to CC anyone else whose perspective would be good on this.

**Comment by ellisonbg** [comment]
Great, we definitely want to have something like this - maybe even in the form of a template. Other places we should pull from :+1: 

Our existing IPEPs:

https://github.com/ipython/ipython/wiki/IPEPs:-IPython-Enhancement-Proposals

The format of the Python Enhancement Proposals:

https://www.python.org/dev/peps/

**Comment by ellisonbg** [comment]
It might also make sense to move our existing IPEPs over here?

**Comment by Carreau** [comment]
+1 let's iterate.

**Comment by rgbkrk** [comment]
I'm not sure if we should move our existing IPEPs over immediately. We should link them in the README, certainly, but we should at least start getting in the EPs that @ssanderson, @parente, and myself want to get out there for people to review, discuss, and provide implementations for.

**Comment by ellisonbg** [comment]
Sounds good

On Fri, Aug 28, 2015 at 8:05 AM, Kyle Kelley <notifications@github.com>
wrote:

> I'm not sure if we should move our existing IPEPs over immediately. We
> should link them in the README, certainly, but we should at least start
> getting in the EPs that @ssanderson <https://github.com/ssanderson>,
> @parente <https://github.com/parente>, and myself want to get out there
> for people to review, discuss, and provide implementations for.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jupyter/enhancement-proposals/pull/1#issuecomment-135799126>
> .
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by parente** [comment]
Already started following the new guidelines (tnx @captainsafia !) in the hackpad copy of the kernel service API. Once all those sections exist, I plan to submit as PR here so we can begin to iterate on it.

**Comment by rgbkrk** [comment]
Would be good to have @jdfreder bring over the discussion/proposal from https://github.com/jupyter/notebook/issues/116 since it has consequences beyond the notebook.

**Pull request merged**
