### PR TITLE
jupyter-incubator/declarativewidgets incorporation proposal

### PR DESCRIPTION
**Pull request by lbustelo**
This PR proposes graduation of the [declarativewidgets extension](https://github.com/jupyter-incubator/declarativewidgets) from jupyter-incubator.

cc'ing folks who either commented on the [original incubation proposal](https://github.com/jupyter-incubator/proposals/pull/4) or are working in related areas: @vinomaster @rgbkrk @ellisonbg @fperez @Carreau @parente @lmeyerov @minrk @damianavila @SylvainCorlay @jdfreder @jasongrout

### CODE REVIEW

**Comment by rgbkrk** [comment]
I'm certainly in support of bringing the declarative widgets in as a supported project by Jupyter.

**Comment by minrk** [comment]
👍

**Comment by minrk** [comment]
Sorry for taking forever on these. Merging as official policy is to [treat silence as agreement](https://github.com/jupyter/governance/blob/master/newsubprojects.md#proposal-for-incorporation).

**Comment by SylvainCorlay** [comment]
I propose this is moved to the `jupyter-widgets` org when we create it for all the ipywidgets subprojects.

**Comment by rgbkrk** [comment]
Thanks @minrk.

**Pull request merged**
