### PR TITLE
add JEP 42 (voila incorporation) to readme

### PR DESCRIPTION
**Pull request by Zsailer**
I realized we forgot to have you add JEP #42 to the front page README.

@SylvainCorlay

### CODE REVIEW

**Comment by SylvainCorlay** [comment]
@blink1073 you beat me to it.

**Comment by SylvainCorlay** [comment]
I am so glad I got number 42.

**Comment by choldgraf** [comment]
question for @SylvainCorlay - is this JEP now "implemented"? If not, what are the steps we need to consider this an implemented JEP?

**Comment by SylvainCorlay** [comment]
> question for @SylvainCorlay - is this JEP (and the one for Xeus) now "implemented"? If not, what are the steps we need to consider this an implemented JEP?

I think this is mostly implemented. One small detail is that the link to gitter still points to the QuantStack gitter channel.

**Comment by choldgraf** [comment]
Whenever you think this is done, we should mark them as completed in the JEP repository - want to make sure that whatever is supposed to happen when a project "becomes a jupyter proejct" actually happens 😅

**Pull request merged**
